---
name: copy some 4 files and install ansible
become: true
hosts:
task:
  - name: copy the output.txt to all slaves
    copy:
      src: /etc/passwd
      dest:
  - name: copy the file1.txt to all slaves
    copy:
      src: /etc/shadow
      dest:
  - name: copy the file2.txt to all slaves
    copy:
      src: /etc/groups
      dest:
  - name: copy the file3.txt to all slaves
    copy:
      src: /etc/ansible/ansible.cfg
      dest:
  - name: install apache
    yum:
      name: httpd
      state: present
